### ISSUE TITLE
Feature Request: After Map Button

### ISSUE THREAD

**Issue by livejamie** [lemasato/POE-Trades-Helper#11]
The "Wait" button is nice if I'm ready to trade right away but I need a quick moment. (Trading with somebody or on a boss)

It would be nice to have another button that was "Later" or something that could respond with "Can I whisper you after lab?" or "After this map", etc.

Thanks!

**Comment by cirf** [comment]
I would like to extend that request to implement a set(maybe 3?) custom buttons in the GUI. Maybe just extend the advanced hotkey menu with a checkbox: "also display a button". You have to have an label field for the button on that case.

**Comment by livejamie** [comment]
Yeah maybe it's better behavior to give the user a set of buttons and allow them to label and define what they do

**Comment by lemasato** [comment]
Added as of 1.6!  

You can now have up to 9 custom buttons.  
To access them, head into the [Settings] tray menu and select the TradesGUI tab.
From there, you can rename the button's label and set it's action.

**Comment by cirf** [comment]
Very nice! thx @lemasato
