### ISSUE TITLE
Feature request: "Back from afk" button

### ISSUE THREAD

**Issue by ricds** [lemasato/POE-Trades-Helper#14]
It would be very helpful if there was a button to reply to someone after you return from afk asking if they still need the requested item.

**Comment by lemasato** [comment]
This has been requested a few times, and is definitely in the works!

**Comment by lemasato** [comment]
Added as of 1.6 as "Still Interested?"!

To enable the button, head into the [Settings] tray menu, click on the TradesGUI tab.  
Set the desired button's HPOS, VPOS and SIZE, then click on Apply Settings.
