### ISSUE TITLE
Message Gets Cut Off

### ISSUE THREAD

**Issue by livejamie** [lemasato/POE-Trades-Helper#16]
See attached image

![image](https://cloud.githubusercontent.com/assets/49513/22280228/1433d3c0-e295-11e6-95e6-5c4db9322190.png)

Thanks!

**Comment by lemasato** [comment]
Thanks for the report,  
I'll be adding a new section that'd contain the additional messages.

**Comment by lemasato** [comment]
Fixed as of 1.7!  
Anything that was added before/after the message will be in the new "Other:" section!
