### ISSUE TITLE
[Feature Request] Allow to use "whispName" as var in advanced messages

### ISSUE THREAD

**Issue by dein0s** [lemasato/POE-Trades-Helper#17]
First of all I'd like to thank you for your job that you're making for the community!
And now to the subj. I'm not familiar with ahk scripting enough (done some simple clickers in the past if that counts :D), so can't do do it by myself. But it'd be really cool to get that var, so I (and not only me I guess) can get rid of other macro and have just "one ring to rule them all" :)

**Comment by lemasato** [comment]
What do you mean "whispName"?  
You can use the %buyerName% variable to reply to the current tab's buyer.

**Comment by dein0s** [comment]
Instead of %buerName% (which is only can be used if that was a trade message), I want to be able to use "whispName" (https://github.com/lemasato/POE-Trades-Helper/blob/master/POE%20Trades%20Helper.ahk#L238) for all other whispers that ain't considered as trade messages (for /whois, /invite and other purpose).
Is it more clear now? English is not my native, soz :|

**Comment by lemasato** [comment]
It corresponds to the last person who whispered you.  
Guess I would add it as %lastWhisper%

**Comment by dein0s** [comment]
Yep, that' what I wanted. Thanks a lot :)

**Comment by lemasato** [comment]
Added as of 1.7!
