### ISSUE TITLE
Feature Request: Leave Party Command

### ISSUE THREAD

**Issue by PocketMedic** [lemasato/POE-Trades-Helper#2]
Hey man!

I am loving this program so much. It is really helping to speed up my trading. However, I was hoping it would be possible to have the option to make the macro kick you or the other player from party when you click the thank you button OR have the option to add additional commands following the text. For example:

"@%buyerName% Thanks mate! // /kick %buyerName%"

Thanks!

**Comment by lemasato** [comment]
That's a nice one.  
I'll be adding a checkbox for it :p

**Comment by PocketMedic** [comment]
You are a champion. Please **never** stop developing this!

**Comment by lemasato** [comment]
Clicking on the "Thanks" button now also kick the buyer out of your party!  
As of being able to use the trade variables in the hotkeys, it still has to be added.
