### ISSUE TITLE
[BUG] Unable to switch back to Advanced Hotkeys because of error

### ISSUE THREAD

**Issue by dein0s** [lemasato/POE-Trades-Helper#20]
Maybe add safe fallback for such kind of inputs (like hotkey itself). Right now only restart helps.
Steps here:
1) On 'Hotkeys' tab switch to 'Advanced'
2) Set any incorrect value in 'hotkey' field (like a!4)
3) Apply settings
4) Switch back to 'Basic'
5) Try to switch to 'Advanced' again
![error](http://i.imgur.com/u5HNOs6.png)

**Comment by lemasato** [comment]
Fixed as of 1.7.3, thanks for reporting!

**Comment by dein0s** [comment]
Yep, works fine now.
Thanks.
