### ISSUE TITLE
[BUG] 'Thank You' button sends raw text in chat instead of performing listed actions

### ISSUE THREAD

**Issue by dein0s** [lemasato/POE-Trades-Helper#21]
I'd guess that it can be somehow related with removed delays and reduced sleep timers in v1.7.3?
I've only changed reply text for this button, so it looks like this:
![button_action](http://i.imgur.com/mu4N5UU.png)
Action text:
`{Enter}/kick %buyerName%{Enter}{Enter}@%buyerName% Thanks and stay safe.{Enter}`
If I set the same action for advanced hotkey - everything works fine.

Steps are:
1) Send yourself a whisper from poe.trade (couldn't test from different account, cos ggg doesn't allow sending trade messages for lowlvl chars)
2) Press 'Thank You' button
![raw_post](http://i.imgur.com/fxJ3Z5o.png)

**Comment by lemasato** [comment]
This is because you are using a Basic message.  
If you wish to perform multiple actions, use an Advanced message.

**Comment by dein0s** [comment]
Hmm, looks like I've accidently switched it or just some magic happened here, because the only change I've done on this settings tab was performed almost a week ago (with previous major release) and I've only changed message text :|
