### ISSUE TITLE
Close trades button?

### ISSUE THREAD

**Issue by leglerm** [lemasato/POE-Trades-Helper#28]
Previously you could manually close pending trades. For example when someone whispered several times so you dont need to thank 5 times. This button (the little X) doesnt exist anymore.

**Comment by leglerm** [comment]
Update/Reload fixed it somehow.

**Comment by lemasato** [comment]
Seems to be the same as [#27](https://github.com/lemasato/POE-Trades-Helper/issues/27).  
During the session where the X disappeared, did you open the [Settings] tray menu > TradesGUI tab and click on the Preview button?
