### ISSUE TITLE
Extra hotkeys no longer work in v1.4.1

### ISSUE THREAD

**Issue by DocHoncho** [lemasato/POE-Trades-Helper#3]
Hello,

I updated to 1.4.1 from 1.3.2.  I have a few hotkeys setup in the Hotkeys tab of the settings.  After the update, the hotkeys still showed up in the settings as active, but do not function in game.

I've tried setting them to different keys, both window modes, and a clean install of 1.4.1.  I also tried deleting Preferences.ini, but nothing has worked.

Happy to provide any additional information you may require.

Thanks

**Comment by Epsynus** [comment]
Experiencing the same issue myself.

**Comment by Epsynus** [comment]
Confirm solved with 1.4.2

**Comment by lemasato** [comment]
Hotkeys are now working correctly again as of 1.4.2!  
Thank you for the reports.
