### ISSUE TITLE
[Bug] Text overlapping

### ISSUE THREAD

**Issue by JYshadow** [lemasato/POE-Trades-Helper#30]
Lovethe program, but sometimes, when a lot messages are coming in, all text in the window start to overlap each other. I have to click through a few of them to un-overlap them.

**Comment by lemasato** [comment]
Thanks for the report,  
I'll make sure the tabs work correctly in the next fix.

**Comment by JYshadow** [comment]
Thanks a lot! Now we're on it anyway: I've also found a bug where the text of the buttons completely disappear. Happens less often, but I do have to reload the script to fix it. Is that also going to be fixed within the same patch?

**Comment by lemasato** [comment]
I haven't seen this issue happen.  
Thanks for the report, if I manage to reproduce the issue, it's definitely going to be part of the next patch.

**Comment by lemasato** [comment]
Fixed as of 1.8.4!
