### ISSUE TITLE
Error with update 1.8.4 - Call to nonexistent function.

### ISSUE THREAD

**Issue by Epsynus** [lemasato/POE-Trades-Helper#31]
Hiya!

I just launched the program and it informed me that there was an update so I let it auto update and it now produces the following error:
```
Error: Call to nonexistent function.
Specifically: Gui_Trades(,"CREATE")
             Line#
---->        070; Gui_Trades(;"CREATE")

The program will exit
```

[Imgur of error](http://i.imgur.com/8NA6Ja7.png)

I tried to download it manually from the github in case something went awry with the auto updater, but the same issue occurs.

**Comment by lemasato** [comment]
Yep, my bad!  
Instantly reverted back to 1.8.3 and pushed 1.8.5.  
I'm really really really sorry for the issue.

**Comment by Epsynus** [comment]
Don't worry mistakes happen and I have to admit, you were really quick with resolving it, haha. Thanks for all your work and keep it up, look forward to future updates! 👍

**Comment by lemasato** [comment]
Anyone who downloaded the 1.8.4 will have to manually update to 1.8.5 [(Right here)](https://github.com/lemasato/POE-Trades-Helper/raw/master/POE%20Trades%20Helper.exe)
