### ISSUE TITLE
Hotkey issue

### ISSUE THREAD

**Issue by Epsynus** [lemasato/POE-Trades-Helper#32]
Hiya again!

So I manually updated to 1.8.5 as per your recommendation, however now I have encountered a strange issue.

In the Hotkey's tab under options I have set a hotkey as ALT+1 to be /kick TonyTonyChopper.
And so far it's always worked!
However with this update it strangely has moved over to be SHIFT+1, and even if I under the hotkeys set it to be either CTRL, ALT or SHIFT. Or all at once. It doesn't take them into account and sticks with just SHIFT+1

Tried resetting the settings under `C:\Users\Epsynus\Documents\AutoHotKey\POE Trades Helper`
by deleting the Preferences file.

I also tried removing the whole program and downloading it again, however the issue still appears when I have setup the keybindings anew.

Any idea what could be the cause?

Pastebin of the latest log:
http://pastebin.com/syTU7Kbi

**Comment by lemasato** [comment]
There was indeed an issue with the hotkeys.  
There was also an issue with the "Cycle Overlay" tray item.  
Both will be fixed in 1.8.7, coming in a few minutes!  
&nbsp;  
Thanks a lot for your reports!

**Comment by Epsynus** [comment]
Can confirm it is now fixed!
Thanks again for your work!
