### ISSUE TITLE
[Feedback] OS Notifications lock up taskbar

### ISSUE THREAD

**Issue by DocHoncho** [lemasato/POE-Trades-Helper#4]
Hello,

When Tray Notifications are enabled, notifications are significantly delayed.  During the delay, the task bar is completely unresponsive.

Interestingly, explorer.exe isn't locked up, alt-tab and such still work, only the taskbar is affected.

The notifications do eventually show up.  It took a bit to put two and two together and realize the taskbar issue was being caused by the notifications.

Happy to provide any additional information you may require.

Thanks

**Comment by lemasato** [comment]
Does it also happen with all the notifications settings disabled (excepted tray notifications)?
I can't seem the reproduce the issue.  
Though, I'm using Win7, so it may be related to Win10.

**Comment by lemasato** [comment]
Does this issue still happen?

**Comment by DocHoncho** [comment]
To answer both questions, no the issues stopped when notification turned
off, and no, I don't believe he issue still occurs.

Unfortunately I do not currently have access to the machine I first
encountered the issue at the moment so I cannot say for certain.

As soon as I can get back on that other machine I'll update the issue with
whether it occurs there or not.

Cheers.

**Comment by lemasato** [comment]
Closing.  
If you ever encounter the issue again, please let me know.
