### ISSUE TITLE
Feature Request: Initiate Trade Command

### ISSUE THREAD

**Issue by Dagda47** [lemasato/POE-Trades-Helper#5]
I don't know if it's worth a button or if it's already gotten thought of but i would like a shortcut to initiate the trade:

/tradewith <character>

Is it possibly to use the appropriate variables in the external makro section? (After it is fixed :D)

**Comment by lemasato** [comment]
Hotkeys will be compatible with the trade variables soon!

**Comment by nassimm** [comment]
Man, this is gonna be the best thing ever !

**Comment by lemasato** [comment]
Trade variables are now compatible with hotkeys.  
The trade variable will use the currently active tab infos.  
&nbsp;
As of the /tradewith button, it's still in the works.

**Comment by lemasato** [comment]
Added as of 1.6 as "Trade Request"!

The button is disabled by default.
To enable the button, head into the [Settings] tray menu, click on the TradesGUI tab.
Set the desired button's HPOS, VPOS and SIZE, then click on Apply Settings.
