### ISSUE TITLE
Feature Request: make the "thanks" button available at all times

### ISSUE THREAD

**Issue by Xebtria** [lemasato/POE-Trades-Helper#8]
Reason being: I also want to thank the seller if I am the buyer. 

also consider #2 in that case - i want to leave the party after saying thanks in that matter (kicking the buyer out of the party when I am the seller is fine for that matter)

additionally, thanks for that already absolutely amazing program.

**Comment by lemasato** [comment]
Unfortunately, this isn't possible.  
I would recommend you to use an hotkey that sends the message in the local/party chat.
