### ISSUE TITLE
[Feedback] Bug: Foreign Characters Don't Display

### ISSUE THREAD

**Issue by livejamie** [lemasato/POE-Trades-Helper#9]
When I use the buyername variable, if the buyer's name is Russian characters it will output in asterisks instead of their actual name.

**Comment by lemasato** [comment]
Does the name appear correctly on the Trades GUI?

**Comment by livejamie** [comment]
Yes that works but the output of %buyerName% in the thanks whisper shows as ********

**Comment by lemasato** [comment]
Using the new version (1.5), can you do a few trades and send me the most recent logs file located in "C:\Users\YourName\Documents\AutoHotkey\POE Trades Helper\Logs" ?

**Comment by livejamie** [comment]
Sure

**Comment by lemasato** [comment]
Does this still happen as of 1.5.1?

**Comment by lemasato** [comment]
Closing the issue.  
If you encounter the issue again, please let me know.
